server:
  port: 8001

spring:
  application:
    #    用户服务消费者
    name: user-service-consumer

#注册中心配置
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:9011/eureka
      prefer-ip-address: true     #访问路径可以显示IP地址
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port} #主机名
    hostname: ${spring.cloud.client.ipAddress}

feign:
  hystrix:
    enabled: true

#ribbon的超时时间, 防止feign调用超时
#ribbon:
#  ReadTimeout: 15000
#  ConnectTimeout: 15000
#  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
#  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
#  OkToRetryOnAllOperations: false  #是否所有操作都重试