#服务名称
spring:
  application:
    name: spring-cloud-eureka

#服务端口
server:
  port: 9011

#注册中心配置
eureka:
  instance:
    hostname: peer1 #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    #表示表示是否从EurekaServer获取注册信息，默认为true。单节点不需要同步其他的EurekaServer节点的数据
    fetch-registry: false
    service-url:
      defaultZone: http://peer1:9011/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
#      http://peer2:9012/eureka/http://peer3:9013/eureka/ 在注册中心集群中，也是默认使用轮询的方式进行
#先负载均衡获取注册中心，再获取消费者服务，消费者再负载均衡获取服务